version: 2.1

executors:
  elixir-executor:
    docker:
      - image: elixir:1.8.1
    working_directory: ~/app

jobs:
  get_dependencies:
    executor: elixir-executor
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - persist_to_workspace:
          root: .
          paths: deps

  test:
    executor: elixir-executor
    steps:
      - checkout
      - run: mix local.hex --force
      - attach_workspace:
          at: deps
      - run: mix test
      - run: mix espec

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - get_dependencies
      - test:
          requires:
            - get_dependencies